### PR TITLE
updated dnscrypt-proxy to 2.0.9

### PR DESCRIPTION
**Pull request by royvou**
This updates dnscrypt-proxy to 2.0.9b.
The significantly less memory usage is the most noteworthy change (from ~130MB to  ~30MB) on my system.

[Changelog at the official repository ](https://github.com/jedisct1/dnscrypt-proxy/releases/tag/2.0.9b1)
- Whitelists have been implemented: one a name matches a pattern in the whitelist, rules from the name-based and IP-based blacklists will be bypassed. Whitelists support the same patterns as blacklists, as well as time-based rules, so that some website can be normally blocked, but accessible on specific days or times of the day.
- Lists are now faster to load, and large lists require significantly less memory than before.
- New options have been added to disable TLS session tickets as well as use a specific cipher suite. See the example configuration file for a recommended configuration to speed up DoH servers on ARM such as Android devices and Raspberry Pi.
- The -service install command now remembers what the current directory was when the service was installed, in order to later load configuration files with relative paths.
- DoH: The "Cache-Control: max-age" header is now ignored.

### CODE REVIEW

**Comment by evilvibes** [comment]
Maybe not a good idea to update to a beta.

**Comment by jedisct1** [comment]
It is a good idea, since this will end up in a SimpleDNSCrypt snapshot.

And more people testing the beta is great!

**Comment by evilvibes** [comment]
Okie dokie

**Comment by royvou** [comment]
And updated to the final version :)

**Comment by bitbeans** [comment]
@royvou thank you! :)

**Pull request merged**
